CREATE TABLE IF NOT EXISTS "beatmaps" (
	"beatmapset_id" integer NOT NULL,
	"difficulty_rating" real NOT NULL,
	"id" integer NOT NULL,
	"mode" text NOT NULL,
	"status" text NOT NULL,
	"total_length" integer NOT NULL,
	"user_id" integer NOT NULL,
	"version" text NOT NULL,
	"accuracy" real NOT NULL,
	"ar" real NOT NULL,
	"bpm" real,
	"convert" boolean NOT NULL,
	"count_circles" integer NOT NULL,
	"count_sliders" integer NOT NULL,
	"count_spinners" integer NOT NULL,
	"cs" real NOT NULL,
	"deleted_at" text,
	"drain" real NOT NULL,
	"hit_length" integer NOT NULL,
	"is_scoreable" boolean NOT NULL,
	"last_updated" text NOT NULL,
	"mode_int" integer NOT NULL,
	"passcount" integer NOT NULL,
	"playcount" integer NOT NULL,
	"ranked" integer NOT NULL,
	"url" text NOT NULL,
	"checksum" text,
	"failtimes" text,
	"max_combo" integer,
	"valid_until" text NOT NULL,
	CONSTRAINT "beatmaps_id_mode_pk" PRIMARY KEY("id","mode")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "beatmapsets" (
	"id" integer PRIMARY KEY NOT NULL,
	"artist" text NOT NULL,
	"artist_unicode" text NOT NULL,
	"creator" text NOT NULL,
	"source" text NOT NULL,
	"tags" text NOT NULL,
	"title" text NOT NULL,
	"title_unicode" text NOT NULL,
	"covers" text NOT NULL,
	"favourite_count" integer NOT NULL,
	"hype" text,
	"nsfw" boolean NOT NULL,
	"offset" integer NOT NULL,
	"play_count" integer NOT NULL,
	"preview_url" text NOT NULL,
	"spotlight" boolean NOT NULL,
	"status" text NOT NULL,
	"track_id" integer,
	"user_id" integer NOT NULL,
	"video" boolean NOT NULL,
	"bpm" real,
	"can_be_hyped" boolean NOT NULL,
	"deleted_at" text,
	"discussion_enabled" boolean NOT NULL,
	"discussion_locked" boolean NOT NULL,
	"is_scoreable" boolean NOT NULL,
	"last_updated" text NOT NULL,
	"legacy_thread_url" text,
	"nominations_summary" text,
	"ranked" integer NOT NULL,
	"ranked_date" text,
	"storyboard" boolean NOT NULL,
	"submitted_date" text,
	"availability" text,
	"has_favourited" boolean,
	"current_nominations" text,
	"description" text,
	"genre" text,
	"langauge" text,
	"pack_tags" text[] DEFAULT '{}'::text[],
	"ratings" integer[] DEFAULT '{}'::int[],
	"related_users" text,
	"user" text,
	"valid_until" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "beatmapsets_files" (
	"id" integer PRIMARY KEY NOT NULL,
	"includes_video" boolean NOT NULL,
	"path" text NOT NULL,
	"checksum" text NOT NULL,
	"updated_at" text DEFAULT now()::timestamp without time zone NOT NULL,
	"created_at" text DEFAULT now()::timestamp without time zone NOT NULL,
	"deleted_at" text,
	"valid_until" text NOT NULL
);
