export enum RedisKeys {
  BEATMAP_BY_ID = "BEATMAP:ID:",
  BEATMAP_ID_BY_HASH = "BEATMAP_ID:HASH:",
  BEATMAPSET_BY_ID = "BEATMAPSET:ID:",
  BEATMAPSET_FILE_BY_ID = "BEATMAPSET_FILE:ID:",
  BEATMAP_OSU_FILE = "BEATMAP_OSU_FILE:ID:",
  DAILY_RATE_LIMIT = "DAILY_RATE_LIMIT:DOMAIN:",
  BEATMAPS_SEARCH_RESULT = "BEATMAPS_SEARCH_RESULT:",
}
